include-paths:
  - "ts/packages/ts/"
  - "ts/packages/node/"
  - "ts/packages/browser/"
name-template: "ts/v$RESOLVED_VERSION"
tag-template: "ts/v$RESOLVED_VERSION"
tag-prefix: "ts/"
# common configurations - https://github.com/release-drafter/release-drafter#configuration-options
include-labels:
  - "feat"
  - "bug"
  - "chore"
exclude-labels:
  - "skip"
category-template: "### $TITLE"
categories:
  - title: "ğŸš€ Features"
    label: "feat"
  - title: "ğŸ› Bug Fixes"
    label: "bug"
  - title: "ğŸ§° Maintenance"
    label: "chore"
version-resolver:
  minor:
    labels:
      - "feat"
  patch:
    labels:
      - "bug"
      - "chore"
  default: "patch"
template: |
  $CHANGES
