name: "CI: Python Tests"
on:
  pull_request:
    branches:
      - main
    paths:
      - "py/**"

jobs:
  ci:
    name: Run pytest
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/py-env-action

      - name: Run black
        run: |
          cd ${{ env.CWD }}
          poetry run black configu

      - name: Run flake8
        run: |
          cd ${{ env.CWD }}
          poetry run flake8 configu

      - name: Run Tests
        run: |
          cd ${{ env.CWD }}
          poetry run pytest
