name: "CI/Pull Request"

on:
  pull_request_target:

jobs:
  ci-pr:
    name: "CI/Pull Request"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - name: PR Assignee
        uses: toshimaru/auto-author-assign@v2.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR Labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/configs/labeler.yml
          sync-labels: true

      - uses: ./.github/actions/get-actor-action
        id: actor
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR Labels
        if: ${{ steps.actor.outputs.actor-permission == 'read' || steps.actor.outputs.actor-permission == 'none' }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "community"

      - name: PR Metrics
        uses: microsoft/PR-Metrics@v1.5.7
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base-size: 200
          growth-rate: 2.0
          test-factor: 0.0
        continue-on-error: true
